### PR TITLE
test pr

### PR DESCRIPTION
**Pull request by bratchenko**
[Review on Reviewable](https://reviewable.io/reviews/bratchenko/jenkins-pr-comments-test/1)

### CODE REVIEW

**Comment by odom-server** [comment]
Test comment

**Comment by odom-server** [comment]
Success!!!

**Comment by odom-server** [comment]
Success!!!

**Comment by odom-server** [comment]
Success!!!

**Comment by kagel** [comment]
- [x] one
- [x] two
- [x] three
- [ ] four

md5 hash: 91b8c336caffcc31e8c92bdb6027b2a0

**Pull request closed without merging**
